<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>agx_arm_controller</name>
  <version>0.1.0</version>
  <description>轨迹下发执行与结果回传节点（规划决策层，C++）。</description>
  <maintainer email="rxp@todo.todo">rxp</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>control_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>agx_motion_msgs</depend>

  <exec_depend>agx_arm_ctrl</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
