[develop]
script_dir=$base/lib/agv_base_driver
[install]
install_scripts=$base/lib/agv_base_driver

[options.entry_points]
console_scripts =
    eth_gateway = agv_base_driver.eth_gateway_node:main
    agv_base_eth_bringe = agv_base_driver.agv_base_eth_bringe_node:main
    cmd_vel_gui = agv_base_driver.cmd_vel_gui_node:main
